Update Recovery-Builder-PBRP.yml
Signed-off-by: ナケヤン-君 <87180225+Nakeyan@users.noreply.github.com>

diff --git a/.github/workflows/Recovery-Builder-PBRP.yml b/.github/workflows/Recovery-Builder-PBRP.yml
--- a/.github/workflows/Recovery-Builder-PBRP.yml
+++ b/.github/workflows/Recovery-Builder-PBRP.yml
@@ -145,7 +145,15 @@ jobs:
         cd android-recovery
         source build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
-        lunch ${{ env.DEVICE_MAKEFILE }}-eng && mka pbrp
+        lunch ${{ env.DEVICE_MAKEFILE }}-eng
+        if [ "${{ github.event.inputs.BUILD_TARGET }}" = "vendorboot" ]; then
+          mka vendorbootimage
+        elif [ "${{ github.event.inputs.BUILD_TARGET }}" = "boot" ]; then
+          mka bootimage
+        else
+          mka recoveryimage
+        fi
+
       
     - name: Set Build Date # Output will be use in Release
       run: |
@@ -164,7 +172,15 @@ jobs:
           Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
           Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
           Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
-
+    
+    - name: Check if vendor_boot.img exists
+      id: check_vendorboot
+      run: |
+        if [ ! -f android-recovery/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img ]; then
+          echo "vendor_boot.img not found!"
+          exit 1
+        fi
+    
     - name: Upload to Release (if vendor_boot)
       if: github.event.inputs.BUILD_TARGET == 'vendorboot'
       uses: softprops/action-gh-release@v1
@@ -178,6 +194,7 @@ jobs:
           Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
           Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
           Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+
 
     - name: Run LDCheck (Only if LDCHECK was set to check.)
       if: github.event.inputs.LDCHECK == 'check'
